# Generated by Django 5.0.7 on 2024-08-06 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('links', models.URLField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_contacted', 'Not Contacted'), ('completed_interested', 'Completed - Interested'), ('completed_not_interested', 'Completed - Not Interested'), ('completed_follow_up_needed', 'Completed - Follow-Up Needed'), ('voicemail_left', 'Voicemail Left'), ('wrong_number', 'Wrong Number'), ('do_not_call', 'Do Not Call'), ('call_back_later', 'Call Back Later'), ('no_answer', 'No Answer'), ('disconnected_number', 'Disconnected Number'), ('appointment_set', 'Appointment Set'), ('in_progress', 'In Progress'), ('need_to_reassign', 'Need to Reassign')], default='not_contacted', max_length=26)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
