# Generated by Django 5.0.7 on 2024-08-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('local_shops', 'Local Shops and Boutiques'), ('online_sellers', 'Online Sellers'), ('healthcare', 'Healthcare Providers'), ('education', 'Education and Coaching Centers'), ('beauty', 'Beauty and Wellness'), ('restaurants', 'Restaurants and Cafes'), ('hotels', 'Hotels and Guesthouses'), ('freelancers', 'Freelancers and Consultants'), ('real_estate', 'Real Estate Agents'), ('manufacturers', 'Small-scale Manufacturers'), ('event_planners', 'Event Planners and Organizers'), ('travel_agencies', 'Travel Agencies')], default='local_shops', max_length=20),
        ),
    ]
